services:
  flask:
    build: .
    expose:
      - "5000"
    volumes:
      - C:/Users/LENOVO/OneDrive/Pictures/Blinkwiggy:/app/images
    networks:
      - blinknet

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    networks:
      - blinknet

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - blinknet
    ports:
      - "6379:6379"

  worker:
    build: .
    command: python worker.py
    volumes:
      - C:/Users/LENOVO/OneDrive/Pictures/Blinkwiggy:/app/images
    depends_on:
      - redis
    networks:
      - blinknet

networks:
  blinknet:
